=== NikolasBdn/xml-SGBD/src/recherche.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT document (SELECT)>
<!ELEMENT SELECT (CHAMPS, TABLES, CONDITION, Signature)>
 <!ELEMENT CHAMPS (CHAMP+)>
    <!ELEMENT CHAMP (#PCDATA)>
 <!ELEMENT TABLES (TABLE+)>
    <!ELEMENT TABLE (#PCDATA)>
 <!ELEMENT CONDITION (#PCDATA)>

 <!-- Signature -->
 <!ELEMENT Signature (SignedInfo, SignatureValue, KeyInfo)>
   <!ATTLIST Signature xmlns CDATA #REQUIRED>

   <!ELEMENT SignedInfo (CanonicalizationMethod, SignatureMethod, Reference)>
      <!ELEMENT CanonicalizationMethod EMPTY>
         <!ATTLIST CanonicalizationMethod Algorithm CDATA #REQUIRED>

      <!ELEMENT SignatureMethod EMPTY>
         <!ATTLIST SignatureMethod Algorithm CDATA #REQUIRED>

      <!ELEMENT Reference (Transforms, DigestMethod, DigestValue)>
         <!ATTLIST Reference URI CDATA #IMPLIED >
         <!ELEMENT Transforms (Transform+)>
            <!ELEMENT Transform EMPTY>
               <!ATTLIST Transform Algorithm CDATA #REQUIRED>

         <!ELEMENT DigestMethod EMPTY>
            <!ATTLIST DigestMethod Algorithm CDATA #REQUIRED>
         
         <!ELEMENT DigestValue (#PCDATA)>


   <!ELEMENT SignatureValue (#PCDATA)>

   <!ELEMENT KeyInfo (KeyValue)>
      <!ELEMENT KeyValue (DSAKeyValue)>
         <!ELEMENT DSAKeyValue (P, Q, G, Y)>
            <!ELEMENT P (#PCDATA)>
            <!ELEMENT Q (#PCDATA)>
            <!ELEMENT G (#PCDATA)>
            <!ELEMENT Y (#PCDATA)>

=== NikolasBdn/xml-SGBD/src/recherche.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE SELECT SYSTEM "recherche.dtd">
<SELECT>
<CHAMPS>
    <CHAMP>nom</CHAMP>
    <CHAMP>prenom</CHAMP>
    <CHAMP>numJoueur</CHAMP>
    <CHAMP>numero</CHAMP>

</CHAMPS>
<TABLES>
    <TABLE>equipe</TABLE>
    <TABLE>joueur</TABLE>
</TABLES>
<CONDITION>codeEquipe = "FRA"</CONDITION>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#dsa-sha1"/><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>gD8d6HuDdLyMBvHU6SvyGFaPeEg=</DigestValue></Reference></SignedInfo><SignatureValue>cdWuzABUeVP6JcmOWzscIYy6n3l1SyDx+FoB9hemej0TEi7CAD2dJg==</SignatureValue><KeyInfo><KeyValue><DSAKeyValue><P>/KaCzo4Syrom78z3EQ5SbbB4sF7ey80etKII864WF64B81uRpH5t9jQTxeEu0ImbzRMqzVDZkVG9&#13;
xD7nN1kuFw==</P><Q>li7dzDacuo67Jg7mtqEm2TRuOMU=</Q><G>Z4Rxsnqc9E7pGknFFH2xqaryRPBaQ01khpMdLRQnG541Awtx/XPaF5Bpsy4pNWMOHCBiNU0Nogps&#13;
QW5QvnlMpA==</G><Y>FJQvXuH0KaW+x3zDfgcee3IJMwYCH15IPg7lL3R9Yx6rzQMBo9nnj/Cz8w05mZExEU0z6MWiOWb6&#13;
bBr6BuZehg==</Y></DSAKeyValue></KeyValue></KeyInfo></Signature></SELECT>
